// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../downloads/weather-compareandalert/node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@b_d50efc5f39b3013dee355276172c6b48/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../downloads/weather-compareandalert/node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0_97006402e0daab7ce14df7eb70816c37/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}