// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.2/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0_97006402e0daab7ce14df7eb70816c37/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7_6dd82468bef62e229e16e6db230f9d29/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7_6dd82468bef62e229e16e6db230f9d29/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/@nuxt+ui@4.7.0_@internation_317b485d9fc764b113a8330aae33f4de/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../downloads/weather-compareandalert/node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29_56f769de628cea253222803387a27e88/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | '@nuxt/icon' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
